### ISSUE TITLE
Is this addon abandoned ?

### ISSUE THREAD

**Issue by dorald** [bgstaal/ofxShivaVG#12]
Any chance to run this addon on on oF 10 ?

**Comment by moebiussurfing** [comment]
hey @dorald ,
I am using this fork on macOS and is working:
https://github.com/numbersinmotion/ofxShivaVG.git

just a trick: you can search in GitHub like this:
ofxShivaVG fork:enable
then you can sort the forks for most recent updated

also, I remember that in the OF forum there's some topic/tricks for ofxShivaVG (or alternatives like ofxNanoVG, ofxFatLines..etc) that I don't remember... One was from Zach, about how to render shiva into an fbo (with custom settings) to not depend on the render settings of different platforms...

**Comment by dorald** [comment]
Hey @moebiussurfing thank you !
This is what i searched for :)
